/**
 * NANP (US/CA) area code → region. Local data only, no API.
 * Covers common NPAs; unknown codes still return the NPA itself.
 */

export type NanpRegion = {
  areaCode: string;
  region: string;
  country: "US" | "CA";
};

/** Compact NPA map (US + Canada). */
const NPA: Record<string, { region: string; country: "US" | "CA" }> = {
  "201": { region: "New Jersey", country: "US" },
  "202": { region: "Washington DC", country: "US" },
  "203": { region: "Connecticut", country: "US" },
  "205": { region: "Alabama", country: "US" },
  "206": { region: "Washington (Seattle)", country: "US" },
  "207": { region: "Maine", country: "US" },
  "208": { region: "Idaho", country: "US" },
  "209": { region: "California (Stockton)", country: "US" },
  "210": { region: "Texas (San Antonio)", country: "US" },
  "212": { region: "New York (Manhattan)", country: "US" },
  "213": { region: "California (Los Angeles)", country: "US" },
  "214": { region: "Texas (Dallas)", country: "US" },
  "215": { region: "Pennsylvania (Philadelphia)", country: "US" },
  "216": { region: "Ohio (Cleveland)", country: "US" },
  "217": { region: "Illinois", country: "US" },
  "218": { region: "Minnesota", country: "US" },
  "219": { region: "Indiana", country: "US" },
  "224": { region: "Illinois", country: "US" },
  "225": { region: "Louisiana", country: "US" },
  "228": { region: "Mississippi", country: "US" },
  "229": { region: "Georgia", country: "US" },
  "231": { region: "Michigan", country: "US" },
  "234": { region: "Ohio", country: "US" },
  "239": { region: "Florida", country: "US" },
  "240": { region: "Maryland", country: "US" },
  "248": { region: "Michigan", country: "US" },
  "251": { region: "Alabama", country: "US" },
  "252": { region: "North Carolina", country: "US" },
  "253": { region: "Washington", country: "US" },
  "254": { region: "Texas", country: "US" },
  "256": { region: "Alabama", country: "US" },
  "260": { region: "Indiana", country: "US" },
  "262": { region: "Wisconsin", country: "US" },
  "267": { region: "Pennsylvania", country: "US" },
  "269": { region: "Michigan", country: "US" },
  "270": { region: "Kentucky", country: "US" },
  "272": { region: "Pennsylvania", country: "US" },
  "276": { region: "Virginia", country: "US" },
  "281": { region: "Texas (Houston)", country: "US" },
  "301": { region: "Maryland", country: "US" },
  "302": { region: "Delaware", country: "US" },
  "303": { region: "Colorado (Denver)", country: "US" },
  "304": { region: "West Virginia", country: "US" },
  "305": { region: "Florida (Miami)", country: "US" },
  "307": { region: "Wyoming", country: "US" },
  "308": { region: "Nebraska", country: "US" },
  "309": { region: "Illinois", country: "US" },
  "310": { region: "California (Los Angeles)", country: "US" },
  "312": { region: "Illinois (Chicago)", country: "US" },
  "313": { region: "Michigan (Detroit)", country: "US" },
  "314": { region: "Missouri (St Louis)", country: "US" },
  "315": { region: "New York", country: "US" },
  "316": { region: "Kansas", country: "US" },
  "317": { region: "Indiana (Indianapolis)", country: "US" },
  "318": { region: "Louisiana", country: "US" },
  "319": { region: "Iowa", country: "US" },
  "320": { region: "Minnesota", country: "US" },
  "321": { region: "Florida", country: "US" },
  "323": { region: "California (Los Angeles)", country: "US" },
  "325": { region: "Texas", country: "US" },
  "330": { region: "Ohio", country: "US" },
  "331": { region: "Illinois", country: "US" },
  "334": { region: "Alabama", country: "US" },
  "336": { region: "North Carolina", country: "US" },
  "337": { region: "Louisiana", country: "US" },
  "339": { region: "Massachusetts", country: "US" },
  "346": { region: "Texas (Houston)", country: "US" },
  "347": { region: "New York (NYC)", country: "US" },
  "351": { region: "Massachusetts", country: "US" },
  "352": { region: "Florida", country: "US" },
  "360": { region: "Washington", country: "US" },
  "361": { region: "Texas", country: "US" },
  "385": { region: "Utah", country: "US" },
  "386": { region: "Florida", country: "US" },
  "401": { region: "Rhode Island", country: "US" },
  "402": { region: "Nebraska", country: "US" },
  "404": { region: "Georgia (Atlanta)", country: "US" },
  "405": { region: "Oklahoma", country: "US" },
  "406": { region: "Montana", country: "US" },
  "407": { region: "Florida (Orlando)", country: "US" },
  "408": { region: "California (San Jose)", country: "US" },
  "409": { region: "Texas", country: "US" },
  "410": { region: "Maryland", country: "US" },
  "412": { region: "Pennsylvania (Pittsburgh)", country: "US" },
  "413": { region: "Massachusetts", country: "US" },
  "414": { region: "Wisconsin (Milwaukee)", country: "US" },
  "415": { region: "California (San Francisco)", country: "US" },
  "417": { region: "Missouri", country: "US" },
  "419": { region: "Ohio", country: "US" },
  "423": { region: "Tennessee", country: "US" },
  "424": { region: "California (Los Angeles)", country: "US" },
  "425": { region: "Washington", country: "US" },
  "430": { region: "Texas", country: "US" },
  "432": { region: "Texas", country: "US" },
  "434": { region: "Virginia", country: "US" },
  "435": { region: "Utah", country: "US" },
  "440": { region: "Ohio", country: "US" },
  "442": { region: "California", country: "US" },
  "443": { region: "Maryland", country: "US" },
  "458": { region: "Oregon", country: "US" },
  "469": { region: "Texas (Dallas)", country: "US" },
  "470": { region: "Georgia (Atlanta)", country: "US" },
  "475": { region: "Connecticut", country: "US" },
  "478": { region: "Georgia", country: "US" },
  "479": { region: "Arkansas", country: "US" },
  "480": { region: "Arizona (Phoenix)", country: "US" },
  "484": { region: "Pennsylvania", country: "US" },
  "501": { region: "Arkansas", country: "US" },
  "502": { region: "Kentucky (Louisville)", country: "US" },
  "503": { region: "Oregon (Portland)", country: "US" },
  "504": { region: "Louisiana (New Orleans)", country: "US" },
  "505": { region: "New Mexico", country: "US" },
  "507": { region: "Minnesota", country: "US" },
  "508": { region: "Massachusetts", country: "US" },
  "509": { region: "Washington", country: "US" },
  "510": { region: "California (Oakland)", country: "US" },
  "512": { region: "Texas (Austin)", country: "US" },
  "513": { region: "Ohio (Cincinnati)", country: "US" },
  "515": { region: "Iowa", country: "US" },
  "516": { region: "New York (Long Island)", country: "US" },
  "517": { region: "Michigan", country: "US" },
  "518": { region: "New York", country: "US" },
  "520": { region: "Arizona (Tucson)", country: "US" },
  "530": { region: "California", country: "US" },
  "531": { region: "Nebraska", country: "US" },
  "534": { region: "Wisconsin", country: "US" },
  "539": { region: "Oklahoma", country: "US" },
  "540": { region: "Virginia", country: "US" },
  "541": { region: "Oregon", country: "US" },
  "551": { region: "New Jersey", country: "US" },
  "559": { region: "California", country: "US" },
  "561": { region: "Florida", country: "US" },
  "562": { region: "California", country: "US" },
  "563": { region: "Iowa", country: "US" },
  "567": { region: "Ohio", country: "US" },
  "570": { region: "Pennsylvania", country: "US" },
  "571": { region: "Virginia", country: "US" },
  "572": { region: "Oklahoma", country: "US" },
  "573": { region: "Missouri", country: "US" },
  "574": { region: "Indiana", country: "US" },
  "575": { region: "New Mexico", country: "US" },
  "580": { region: "Oklahoma", country: "US" },
  "585": { region: "New York", country: "US" },
  "586": { region: "Michigan", country: "US" },
  "601": { region: "Mississippi", country: "US" },
  "602": { region: "Arizona (Phoenix)", country: "US" },
  "603": { region: "New Hampshire", country: "US" },
  "605": { region: "South Dakota", country: "US" },
  "606": { region: "Kentucky", country: "US" },
  "607": { region: "New York", country: "US" },
  "608": { region: "Wisconsin", country: "US" },
  "609": { region: "New Jersey", country: "US" },
  "610": { region: "Pennsylvania", country: "US" },
  "612": { region: "Minnesota (Minneapolis)", country: "US" },
  "614": { region: "Ohio (Columbus)", country: "US" },
  "615": { region: "Tennessee (Nashville)", country: "US" },
  "616": { region: "Michigan", country: "US" },
  "617": { region: "Massachusetts (Boston)", country: "US" },
  "618": { region: "Illinois", country: "US" },
  "619": { region: "California (San Diego)", country: "US" },
  "620": { region: "Kansas", country: "US" },
  "623": { region: "Arizona (Phoenix West Valley)", country: "US" },
  "626": { region: "California", country: "US" },
  "628": { region: "California (San Francisco)", country: "US" },
  "629": { region: "Tennessee", country: "US" },
  "630": { region: "Illinois", country: "US" },
  "631": { region: "New York", country: "US" },
  "636": { region: "Missouri", country: "US" },
  "641": { region: "Iowa", country: "US" },
  "646": { region: "New York (Manhattan)", country: "US" },
  "650": { region: "California (Peninsula)", country: "US" },
  "651": { region: "Minnesota", country: "US" },
  "657": { region: "California", country: "US" },
  "660": { region: "Missouri", country: "US" },
  "661": { region: "California", country: "US" },
  "662": { region: "Mississippi", country: "US" },
  "667": { region: "Maryland", country: "US" },
  "669": { region: "California (San Jose)", country: "US" },
  "678": { region: "Georgia (Atlanta)", country: "US" },
  "681": { region: "West Virginia", country: "US" },
  "682": { region: "Texas", country: "US" },
  "701": { region: "North Dakota", country: "US" },
  "702": { region: "Nevada (Las Vegas)", country: "US" },
  "703": { region: "Virginia", country: "US" },
  "704": { region: "North Carolina (Charlotte)", country: "US" },
  "706": { region: "Georgia", country: "US" },
  "707": { region: "California", country: "US" },
  "708": { region: "Illinois", country: "US" },
  "712": { region: "Iowa", country: "US" },
  "713": { region: "Texas (Houston)", country: "US" },
  "714": { region: "California (Orange County)", country: "US" },
  "715": { region: "Wisconsin", country: "US" },
  "716": { region: "New York", country: "US" },
  "717": { region: "Pennsylvania", country: "US" },
  "718": { region: "New York (NYC)", country: "US" },
  "719": { region: "Colorado", country: "US" },
  "720": { region: "Colorado (Denver)", country: "US" },
  "724": { region: "Pennsylvania", country: "US" },
  "725": { region: "Nevada (Las Vegas)", country: "US" },
  "727": { region: "Florida", country: "US" },
  "731": { region: "Tennessee", country: "US" },
  "732": { region: "New Jersey", country: "US" },
  "734": { region: "Michigan", country: "US" },
  "737": { region: "Texas (Austin)", country: "US" },
  "740": { region: "Ohio", country: "US" },
  "743": { region: "North Carolina", country: "US" },
  "747": { region: "California", country: "US" },
  "754": { region: "Florida", country: "US" },
  "757": { region: "Virginia", country: "US" },
  "760": { region: "California", country: "US" },
  "762": { region: "Georgia", country: "US" },
  "763": { region: "Minnesota", country: "US" },
  "765": { region: "Indiana", country: "US" },
  "769": { region: "Mississippi", country: "US" },
  "770": { region: "Georgia (Atlanta)", country: "US" },
  "772": { region: "Florida", country: "US" },
  "773": { region: "Illinois (Chicago)", country: "US" },
  "774": { region: "Massachusetts", country: "US" },
  "775": { region: "Nevada", country: "US" },
  "779": { region: "Illinois", country: "US" },
  "781": { region: "Massachusetts", country: "US" },
  "785": { region: "Kansas", country: "US" },
  "786": { region: "Florida (Miami)", country: "US" },
  "801": { region: "Utah (Salt Lake City)", country: "US" },
  "802": { region: "Vermont", country: "US" },
  "803": { region: "South Carolina", country: "US" },
  "804": { region: "Virginia", country: "US" },
  "805": { region: "California", country: "US" },
  "806": { region: "Texas", country: "US" },
  "808": { region: "Hawaii", country: "US" },
  "810": { region: "Michigan", country: "US" },
  "812": { region: "Indiana", country: "US" },
  "813": { region: "Florida (Tampa)", country: "US" },
  "814": { region: "Pennsylvania", country: "US" },
  "815": { region: "Illinois", country: "US" },
  "816": { region: "Missouri (Kansas City)", country: "US" },
  "817": { region: "Texas (Fort Worth)", country: "US" },
  "818": { region: "California (Los Angeles)", country: "US" },
  "828": { region: "North Carolina", country: "US" },
  "830": { region: "Texas", country: "US" },
  "831": { region: "California", country: "US" },
  "832": { region: "Texas (Houston)", country: "US" },
  "843": { region: "South Carolina", country: "US" },
  "845": { region: "New York", country: "US" },
  "847": { region: "Illinois", country: "US" },
  "848": { region: "New Jersey", country: "US" },
  "850": { region: "Florida", country: "US" },
  "856": { region: "New Jersey", country: "US" },
  "857": { region: "Massachusetts (Boston)", country: "US" },
  "858": { region: "California (San Diego)", country: "US" },
  "859": { region: "Kentucky", country: "US" },
  "860": { region: "Connecticut", country: "US" },
  "862": { region: "New Jersey", country: "US" },
  "863": { region: "Florida", country: "US" },
  "864": { region: "South Carolina", country: "US" },
  "865": { region: "Tennessee", country: "US" },
  "870": { region: "Arkansas", country: "US" },
  "872": { region: "Illinois (Chicago)", country: "US" },
  "878": { region: "Pennsylvania", country: "US" },
  "901": { region: "Tennessee (Memphis)", country: "US" },
  "903": { region: "Texas", country: "US" },
  "904": { region: "Florida (Jacksonville)", country: "US" },
  "906": { region: "Michigan", country: "US" },
  "907": { region: "Alaska", country: "US" },
  "908": { region: "New Jersey", country: "US" },
  "909": { region: "California", country: "US" },
  "910": { region: "North Carolina", country: "US" },
  "912": { region: "Georgia", country: "US" },
  "913": { region: "Kansas", country: "US" },
  "914": { region: "New York", country: "US" },
  "915": { region: "Texas (El Paso)", country: "US" },
  "916": { region: "California (Sacramento)", country: "US" },
  "917": { region: "New York (NYC mobile overlay)", country: "US" },
  "918": { region: "Oklahoma", country: "US" },
  "919": { region: "North Carolina", country: "US" },
  "920": { region: "Wisconsin", country: "US" },
  "925": { region: "California", country: "US" },
  "928": { region: "Arizona", country: "US" },
  "929": { region: "New York (NYC)", country: "US" },
  "930": { region: "Indiana", country: "US" },
  "931": { region: "Tennessee", country: "US" },
  "936": { region: "Texas", country: "US" },
  "937": { region: "Ohio", country: "US" },
  "938": { region: "Alabama", country: "US" },
  "940": { region: "Texas", country: "US" },
  "941": { region: "Florida", country: "US" },
  "947": { region: "Michigan", country: "US" },
  "949": { region: "California", country: "US" },
  "951": { region: "California", country: "US" },
  "952": { region: "Minnesota", country: "US" },
  "954": { region: "Florida", country: "US" },
  "956": { region: "Texas", country: "US" },
  "959": { region: "Connecticut", country: "US" },
  "970": { region: "Colorado", country: "US" },
  "971": { region: "Oregon (Portland)", country: "US" },
  "972": { region: "Texas (Dallas)", country: "US" },
  "973": { region: "New Jersey", country: "US" },
  "978": { region: "Massachusetts", country: "US" },
  "979": { region: "Texas", country: "US" },
  "980": { region: "North Carolina", country: "US" },
  "984": { region: "North Carolina", country: "US" },
  "985": { region: "Louisiana", country: "US" },
  "986": { region: "Idaho", country: "US" },
  "989": { region: "Michigan", country: "US" },
  // Canada
  "204": { region: "Manitoba", country: "CA" },
  "226": { region: "Ontario", country: "CA" },
  "236": { region: "British Columbia", country: "CA" },
  "249": { region: "Ontario", country: "CA" },
  "250": { region: "British Columbia", country: "CA" },
  "289": { region: "Ontario", country: "CA" },
  "306": { region: "Saskatchewan", country: "CA" },
  "343": { region: "Ontario", country: "CA" },
  "365": { region: "Ontario", country: "CA" },
  "403": { region: "Alberta", country: "CA" },
  "416": { region: "Ontario (Toronto)", country: "CA" },
  "418": { region: "Quebec", country: "CA" },
  "431": { region: "Manitoba", country: "CA" },
  "437": { region: "Ontario (Toronto)", country: "CA" },
  "438": { region: "Quebec (Montreal)", country: "CA" },
  "450": { region: "Quebec", country: "CA" },
  "506": { region: "New Brunswick", country: "CA" },
  "514": { region: "Quebec (Montreal)", country: "CA" },
  "519": { region: "Ontario", country: "CA" },
  "548": { region: "Ontario", country: "CA" },
  "579": { region: "Quebec", country: "CA" },
  "581": { region: "Quebec", country: "CA" },
  "587": { region: "Alberta", country: "CA" },
  "604": { region: "British Columbia (Vancouver)", country: "CA" },
  "613": { region: "Ontario (Ottawa)", country: "CA" },
  "639": { region: "Saskatchewan", country: "CA" },
  "647": { region: "Ontario (Toronto)", country: "CA" },
  "672": { region: "British Columbia", country: "CA" },
  "705": { region: "Ontario", country: "CA" },
  "709": { region: "Newfoundland and Labrador", country: "CA" },
  "778": { region: "British Columbia", country: "CA" },
  "780": { region: "Alberta", country: "CA" },
  "782": { region: "Nova Scotia / PEI", country: "CA" },
  "807": { region: "Ontario", country: "CA" },
  "819": { region: "Quebec", country: "CA" },
  "825": { region: "Alberta", country: "CA" },
  "867": { region: "Yukon / NWT / Nunavut", country: "CA" },
  "873": { region: "Quebec", country: "CA" },
  "879": { region: "Newfoundland and Labrador", country: "CA" },
  "902": { region: "Nova Scotia / PEI", country: "CA" },
  "905": { region: "Ontario", country: "CA" },
};

const TOLL_FREE = new Set(["800", "833", "844", "855", "866", "877", "888"]);

export function lookupNanp(nationalNumber: string): NanpRegion | null {
  const n = String(nationalNumber || "").replace(/\D/g, "");
  if (n.length < 10) return null;
  const areaCode = n.length === 11 && n.startsWith("1") ? n.slice(1, 4) : n.slice(0, 3);
  if (TOLL_FREE.has(areaCode)) {
    return { areaCode, region: "Toll free (NANP)", country: "US" };
  }
  const hit = NPA[areaCode];
  if (hit) return { areaCode, region: hit.region, country: hit.country };
  return { areaCode, region: `NANP area ${areaCode}`, country: "US" };
}

export function isNanpTollFree(nationalNumber: string): boolean {
  const n = String(nationalNumber || "").replace(/\D/g, "");
  const area = n.length === 11 && n.startsWith("1") ? n.slice(1, 4) : n.slice(0, 3);
  return TOLL_FREE.has(area);
}
